language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - scripts/fetch_venues.py bangalore
  - scripts/fetch_venues.py hyderabad
after_script:
  - scripts/travis-update-venues.sh
